lib/docker2aci.go
lib/docker_functions.go
lib/docker_types.go
lib/types.go

We depended on docker packages to use docker's json manifest structures
and to parse the registry URLs but they're in packages `parsers`,
`registry` and `runconfig` which are quite general and have a lot of
dependencies. This caused Godep to download a big chunk of docker's code
which is not desirable when integrating docker2aci with rocket, for
example.
This commit extracts the needed docker functions and structures so we
don't import docker packages anymore.

Remove docker dependencies

---

main.go

It introduces a dependency on rocket and it should be handled by another
tool.
Fixes #11

docker2aci: remove import cmd

---

lib/docker2aci.go

Use Entrypoint + Cmd when both are present or just Cmd when Entrypoint
is not present.
Since non-absolute paths are not allowed by the spec, if the resulting
command is not absolute we fall back to running it with "/bin/sh -c".
Fixes #14

Handle Entrypoint and Cmd correctly

---

lib/docker2aci.go

We were taking the name without layerID as the part before the first
dash. This is wrong because a name can have dashes.
Fix it by taking the part before the last dash.

Fix squashed image name

---

lib/docker2aci.go

Fixes an issue with an index out of range panic when processing a layer that
has no entry point or command specified. Simply adds a length check before
accessing the slice.
Discovered and tested against the `apcera/gnatsd` docker image.

Fix handling of layers with no entrypoint or command

---

lib/docker2aci.go
lib/util.go

If we don't quote every element of the command array, spaces inside
elements will be interpreted by the shell as separators.
Fixes coreos/rocket#631

Quote COMMAND in /bin/sh -c COMMAND

---

README.md
lib/conversion_store.go
lib/docker2aci.go

Until now we were generating ACIs as uncompressed tars. This compresses
the generated ACIs with gzip.
Fixes #31

Generate compressed acis

---

lib/docker2aci.go
lib/util.go

We were ignoring Docker's whiteout files so it's time to handle them.
To do that, we keep a white list of files (PathWhitelist). As we go
through the layers, we remove any files maked as whiteouts from the list
so so that, at any time, each layer ACI has the list of its desired
files and the ones of its parent layers.
We change order we process the images to start from the base image so
that we can generate the correct white lists. Then we reverse the image
list because acirenderer expects images starting from the upper layer.

Handle whiteout files

---

lib/backend/repository/repository.go
lib/common/common.go
lib/common/docker_functions.go
lib/docker2aci.go
lib/types/docker_types.go
main.go

This adds username and password parameters to Convert() so users can
convert images that require authentication.
It also adds a public function GetDockercfgAuth() that parses a
.dockercfg file and returns the credentials of the given Docker index
server.
Finally, another public function GetIndexName() is provided so the user
can know which Docker index server corresponds to a Docker registry URL.
Addresses #7

Add authentication

---

lib/common/common.go

If we use known-to-be-valid strings when creating new ACNames or if we
previously called SanitizeACName we know the creation won't fail.

Use MustACName when we know creation won't fail

---

README.md
lib/common/common.go
main.go

A Docker image can specify Volumes which are akin to mountPoints in the
appc spec. This commit converts Volumes to mountPoints allowing the user
to mount volumes with rkt's --volume option.
Since Docker doesn't name Volumes but the appc spec requires a name, we
generate a name by appending the path to "volume-". That is, if a Volume
has "/var/tmp" as path, the resulting mountPoint name will be
"volume-/var/tmp". A mountPoint name must be a valid ACName so any
invalid characters will be replaced by a "-".

Convert Docker Volumes to mountPoints

---

lib/common/common.go

If a directory is whited out, subtractWhiteouts should remove from
pathWhiteList also all the files inside it.

common: remove from pathWhiteList also files inside withed out directories.

---

lib/common/common.go

The spec changed the field name in types.Dependency from App to
ImageName.
Fixes #62

common: rename App to ImageName

---

main.go

docker2aci.ConvertXXX() has a new parameter which wasn't added to
main.go
Setting to "/tmp".

Fixed the build of docker2aci

---

lib/backend/file/file.go
lib/backend/repository/repository.go
lib/common/common.go
lib/docker2aci.go

First, this revert a patch so that docker2aci compiles against appc/spec v0.5.2 rather than just git-master. It will be useful for rkt, see https://github.com/coreos/rkt/pull/929#issuecomment-104787060.
Then, add the tmpDir parameter to fix #50. It was partially done in #51 but not completely.

lib: add the tmpDir parameter (again)

---

lib/common/common.go
main.go

Convert docker ExposedPorts to appc's []types.Port.
The Name field is taken from docker's port representation (e.g. "8080"
or "8080/udp") and port number and protocol are converted in the obvious
way. If the docker image doesn't specify a protocol, we assume tcp[1]
Also, support deprecated docker PortSpecs.
[1]: https://github.com/docker/docker/blob/master/image/spec/v1.md

common: convert docker ports

---

lib/common/common.go
lib/conversion_store.go
lib/docker2aci.go

Hi,
docker2aci wasn't building anymore so I tried to fix this by changing ACName to ACIdentifier where needed.
I think this was broken since https://github.com/appc/spec/pull/398 has been merged.

Fix build by replacing ACName with ACIdentifier as in the spec

---

lib/common/common.go

We forgot to add the arch label when converting Docker layer data to an
image manifest.

common: add arch label to the manifest

---

lib/common/common.go

This patch tries to implement the idea from #15.
This adds additional docker informations to the image manifest.
Now the v1 registry informations are added under the `appc.io/docker/v1/`
namespace:
`appc.io/docker/v1/indexurl`
`appc.io/docker/v1/repository`
`appc.io/docker/v1/tag`
`appc.io/docker/v1/imageid`
`appc.io/docker/v1/parentimageid`
Before adding a WELLKNOWN.md like proposed I'd like to get suggestions on the annotation names. For example `indexurl` should be `registryurl`?
This can be useful for getting docker v1 caching infos like proposed in https://github.com/coreos/rkt/issues/1196#issuecomment-127983674 without the need to save the imageID info in a store sql table.

common: add additional docker informations to manifest.

---

lib/common/common.go

Now we have to pass to functions wanting a *tar.Reader the embedded *tar.Reader
in aci.TarReadCloser and call the Close() method when finished.
See appc/spec#461

common: update to new appc/spec aci.TarReadCloser.

---

lib/backend/file/file.go

I got tired of my `/tmp` filling up.  So lets not fill it up.

file: cleanup tmpDir

---

lib/common/common.go

We're doing that in generated image names so for dependencies to work we
need to do it too.

common: omit parent index URL if default index

---

lib/conversion_store.go

The interface for aci.NewCompressedReader changed in appc to return a
ReadCloser so we're resposible for closing it.

lib: close aci.NewCompressedReader

---

lib/docker2aci.go

acirenderer adds a rootfs entry since
https://github.com/appc/spec/pull/437
Hence, we need to ignore it because we write our own rootfs entry.
Fixes #94

lib: fix multiple rootfs entries

---

lib/conversion_store.go

When aci.NewCompressedReader was changed to return a ReadCloser, we
changed the code in ReadStream to close it and then wrapped it with a
NopCloser. That was obviously wrong although it didn't seem to have any
effect.
Let's return the ReadCloser directly instead.

lib: don't close reader inside ReadStream

---

lib/common/common.go

Docker images expect /dev/stdin, /dev/stdout, /dev/stderr and /dev/fd
(https://github.com/opencontainers/runc/blob/master/libcontainer/SPEC.md#filesystem)
but appc/spec doesn't
(https://github.com/appc/spec/blob/master/spec/OS-SPEC.md#devices-and-file-systems).
This adds the mentioned symlinks to the converted ACIs so apps can find them as expected.
Fixes #96

common: create stdio symlinks if not present

---

lib/docker2aci.go
tests/test-basic/Dockerfile
tests/test-basic/check.sh
tests/test-whiteouts/Dockerfile
tests/test-whiteouts/check.sh
tests/test.sh

Replace #100 to trigger the tests in Semaphore.
Compared to the previous version:
- no changes with `--nosquash`: no `.hidden` files anymore
- include tests
-----
Hard links and whiteout were not handled correctly in this scenario:
- The first Docker layer contains:
- file A
- file B hard link to file A
- The second Docker layer contains:
- whiteout file A
Then, the squashed ACI previously generated by docker2aci contained:
- file B dangling hard link to file A
Hence the bug.
This patch changes the squashing algorithm lib/docker2aci.go:SquashLayers()
to have two passes:
- Pass one: build an in-memory map of hard links and whiteouts
- Pass two: write the archive using the map generated in pass one
I tested the following images from https://github.com/coreos/rkt/issues/1653:
- …

handle hard links and whiteouts correctly (v3)

---

lib/common/common.go

Basically, we sort every golang map before serializing the Image
Manifest.
There's still a problem with PaxHeaders causing generated some ACIs to be
non-deterministic (https://github.com/appc/docker2aci/issues/89).

common: make manifests deterministic

---

lib/backend/file/file.go
lib/backend/repository/repository.go
lib/backend/repository/repository1.go
lib/backend/repository/repository2.go
lib/common/common.go
lib/common/docker_functions.go
lib/docker2aci.go
main.go

Will detect when fetching an image if the V2 API is supported, and fall
back to the V1 API if it is not. Auth currently unsupported.
Partially addresses https://github.com/appc/docker2aci/issues/46 and https://github.com/coreos/rkt/issues/1583.

adds support for the V2 HTTP API

---

README.md
lib/backend/file/file.go
lib/backend/repository/repository.go
lib/backend/repository/repository1.go
lib/backend/repository/repository2.go
lib/common/common.go
lib/docker2aci.go
main.go

This adds a `--compression` flag which can take the values `gzip` and
`none`. It is enum-like rather than boolean to allow xz and bzip2 to be
added later.
Refs #110

Allow disabling compression

---

lib/backend/repository/repository2.go

It was causing authenticated docker fetches to fail.

backend/repository2: set auth headers for getLayer

---

lib/common/common.go

Since https://github.com/appc/spec/pull/527 the spec allows relative
paths in App.Exec, so we don't need to prepend "/bin/sh -c".

lib: allow relative paths in ImageManifest's App.Exec

---

lib/backend/repository/repository.go
lib/backend/repository/repository1.go
lib/backend/repository/repository2.go
lib/docker2aci.go

If docker2aci is passed the `--insecure` flag, don't directly use http but
try https first and then http.
Helps with https://github.com/coreos/rkt/issues/2036

lib/backend/repository: handle http and https gracefully

---

lib/backend/repository/repository.go

I added this statement to force using Docker API v1 and test if it
worked and I forgot to remove it before pushing :$.

lib/repository: do not force Docker API v1

---

lib/common/common.go
lib/common/docker_functions.go

If the Docker reference does not include any servers, we assume it's a
using the default Docker registry.
Since the Docker API v1 was deprecated in the default registry, we can
now infer the default docker registry name (registry-1.docker.io).
Needed to fix https://github.com/coreos/rkt/issues/2008

lib/common: infer default docker registry

---

lib/backend/repository/repository.go
lib/backend/repository/repository2.go
lib/common/common.go
lib/common/docker_functions.go
lib/docker2aci.go
lib/types/docker_types.go

This PR is fixing:
- fix layers in manifest before downloading them (upstream docker also does this)
- support for downloading images in the Docker Hub that are private
- fix Docker cofing for auth resolution (.dockercfg is obsolete, but I'll support it as a backup)
- if --insecure is provided - set InsecureSkipVerify in client's Transport
I left some TODO(s) as I'm continue working on it (probably will make a followup PR if this gets merged), I left some comments in the code, feel free to comment also.
@philips @jonboulle 
I'd like to have an ack to go ahead and clean this code and commits(if you accept this change) 
pull against Docker hub and private repositories:
BEFORE (wrong config file auths)
```
./bin/docker2aci --debug docker://runcom/busyboxt
Getting image info...
Error: …
```

support authentication, fix layers

---

lib/common/common.go
tests/rkt-v0.16.0.md5sum
tests/rkt-v1.1.0.md5sum
tests/test-pwl/Dockerfile
tests/test-pwl/check.sh
tests/test.sh

In f78ecc1d6e7c3fd913b0d374f759a5b6d3a628f2, we started sorting every
golang map before serializing the Image Manifests to make the generated
ACIs deterministic (golang randomizes maps).
This causes problems with squashed ACIs: they're missing some files (see
https://github.com/coreos/rkt/issues/2244 for some examples).
The reason for this is that we were modifying the PathWhitelist inside
writeACI() and then reusing the same copy in the next iteration of the
loop in convertReal(). Making a copy of the modified PathWhitelist when
we generate the layer's manifest fixes the problem.
cc @krnowak

lib/common: make a copy of pwl instead of reusing the same var

---

build.sh

Using `/usr/bin/env bash` instead of `/bin/bash` makes the build script
a little more portable, as it's not always safe to assume that
`/bin/bash` exists (for example, this is the case in NixOS).

build: use `/usr/bin/env bash` instead of `/bin/bash`

---

README.md
build.sh
lib/backend/file/file.go
lib/conversion_store.go
lib/docker2aci.go
lib/version.go
main.go

This PR includes commits that prepare the first docker2aci release:
* Clean the API by reducing the exposed functions and using config structs instead of individual parameters.
* Decouple an library error message from the docker2aci CLI
* Change the names of the Convert functions
* Exit with status 2 when the arguments are invalid
* Add version flag
* Update build instructions

*: prepare release

---

build.sh

We're vendoring the dependencies now, there's no need to fetch them.

build.sh: remove fetching dependencies

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/docker/distribution/LICENSE
Godeps/_workspace/src/github.com/docker/distribution/digest/digest.go
Godeps/_workspace/src/github.com/docker/distribution/digest/digester.go
Godeps/_workspace/src/github.com/docker/distribution/digest/doc.go
Godeps/_workspace/src/github.com/docker/distribution/digest/set.go
Godeps/_workspace/src/github.com/docker/distribution/digest/verifiers.go
Godeps/_workspace/src/github.com/docker/distribution/reference/reference.go
Godeps/_workspace/src/github.com/docker/distribution/reference/regexp.go
lib/internal/docker/docker_functions.go
lib/internal/types/types.go

Now that we vendor, we can get rid of some copied code.
Also, this might help with https://github.com/coreos/rkt/issues/2188
cc @dgonyeo

lib: use upstream functions and parse digest

---

lib/internal/internal.go

can't serialize them with a join as exec arguments can have a space

change docker entrypoint/cmd annotations to json

---

lib/internal/backend/repository/repository.go
lib/internal/backend/repository/repository2.go
lib/internal/util/util.go

Creating a transport like &http.Transport{} and modifying its
TLSClientConfig turns off proxy support.

util, repository: Use a default transport

---

lib/internal/backend/repository/repository2.go

Fix for case where service has a space in it (e.g., service="Docker regsitry").

Fix auth token parse to handle service with space.

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/coreos/pkg/LICENSE
Godeps/_workspace/src/github.com/coreos/pkg/NOTICE
Godeps/_workspace/src/github.com/coreos/pkg/progressutil/iocopy.go
Godeps/_workspace/src/github.com/coreos/pkg/progressutil/progressbar.go
lib/docker2aci.go
lib/internal/backend/file/file.go
lib/internal/backend/repository/repository.go
lib/internal/backend/repository/repository1.go
lib/internal/backend/repository/repository2.go
lib/internal/internal.go

This is #152 with a bugfix.
> To reduce the time it takes to fetch docker images, this commit modifies
the backends to pull each image layer concurrently. As a result,
github.com/coreos/pkg/progressutil is used in place of ioprogress to
draw the progress bars.

backend/repository: pull layers in parallel

---

lib/internal/backend/repository/repository1.go

Without this it hangs forever when layers are succesfully downloaded.

Added missing message to channel on succesful layer download

---

lib/internal/backend/repository/repository2.go

If any layers being fetched encountered an error, that won't be caught
by the main goroutine until after it's attempted to close all of the
HTTP bodies, but if there was an error the body could be nil. The bodies
should be closed before checking for errors, as there may be some valid
connections, but each body should only be closed if it's not nil.
This commit adds that nil check.
Fixes (at least when I run the test locally) https://semaphoreci.com/coreos/rkt/branches/pull-request-2691/builds/3
cc @iaguis

lib/internal/backend/repository: check if closer is nil before closing

---

lib/common/common.go
lib/docker2aci.go
lib/internal/backend/repository/repository.go
lib/internal/backend/repository/repository1.go
lib/internal/backend/repository/repository2.go
main.go

--insecure flag is removed as it was ambiguous
Two flags are added to replace it:
--insecure-skip-verify: Don't verify certificates when fetching images
--insecure-allow-http: Allows to use unencrypted connections when
fetching images
It solves existing related issues with insecure docker v1 registries
Continuation of #109 and #155, probably related with #144.

Split --insecure flag in two

---

lib/internal/backend/repository/repository2.go

The parallel pull refactoring in
47f2cb963409a14fb765eeb2c7e9ad0fa34ed448 introduced an unfortunate and
subtle race condition. Because i) we were asynchronously starting the
fetching of each layer [1][1] (which implies that the fetch is added to
the progress bar asynchronously, via getLayerV2 [2][2] [3][3]), and ii)
the progressutil package has no guards against calling PrintAndWait and
AddCopy in indeterminate order [4][4], it was possible for us to enter
the PrintAndWait loop [5][5] [6][6] before all of the layer fetches had
actually been added to it. Then, in the event that the first layer was
particularly fast, the CopyProgressPrinter could actually think it was
done [7][7] before the other layer(s) had finished. In this situation,
docker2aci would happily continue forward and try to …

lib/repository2: fix parallel pull synchronisation

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/coreos/pkg/progressutil/iocopy.go
Godeps/_workspace/src/github.com/coreos/pkg/progressutil/progressbar.go
lib/internal/backend/repository/repository2.go

This bumps github.com/coreos/pkg/progressutil to v2, fixing the races from https://github.com/coreos/pkg/pull/64.

lib/repository2: use new progressutil interface

---

lib/internal/backend/repository/repository2.go

The code for pulling from a v2 repository always used the tag to pull,
but the correct action was to pull by digest when one was specified.
Related: https://github.com/appc/docker2aci/issues/170.

backend/repository2: don't ignore when there's an image digest

---

lib/internal/backend/repository/repository.go
lib/internal/backend/repository/repository2.go

- First commit deals with an O(N) routine and removes it (the last layer ID index takes N-1 cycle to be found)
- Second commit remove a reader close call because the reader is used after the function returns

avoid O(N) and fix defer reader close

---

lib/internal/internal.go
lib/tests/common.go
lib/tests/server.go
lib/tests/v22_test.go
tests/test.sh

This commit creates the directory lib/tests, which includes the
following:
- code for generating a manifest and layers conforming to docker v2.2
- code for emulating a docker registry that hosts these images (the
docker daemon can successfully pull images from this)
- a few tests that utilize these to test using the docker2aci library
to pull/convert an image
These fetching tests triggered a panic in docker2aci, which this commit also fixes.
I intend to create a followup PR to also test the docker v2.1 logic and the logic for converting a file on disk, and to hopefully pull the logic under tests/ into these golang tests.

tests: added golang tests to lib/tests to test image fetching

---

lib/internal/backend/repository/repository2.go
lib/tests/v22_test.go

In da56c93f we introduced an optimization to avoid going through all the
layers every time we need the index of a specific one.
However, when we set the layer index, we weren't setting the reversed
index, like we were doing before the optimization.
Fix it by setting the correct index.
Fixes #184

repository2: populate reverseLayers correctly

---

lib/tests/v22_test.go

We forgot to remove it when refactoring it to a function.
Since we're touching this, let's simplify the code a bit.

tests: remove redundant code and simplify code

---

lib/internal/backend/repository/repository.go
lib/internal/backend/repository/repository2.go

In da56c93f we introduced an optimization to avoid going through all the
layers every time we need the index of a specific one.
However, this resulted in incorrect Image Manifests being generated.
In f8e82fab we attempted to fix this. We assumed that the mistake was
that the index we used was supposed to be reversed (from the end instead
of from the beginning of the layer list). This assumption was wrong. and
was probably motivated by the name of the map (`reverseLayers`).
The problem was that there can be several layers with the same BlobSum
(layerID) but different manifest and when we populated the map, we were
storing the last one for a given BlobSum. This is not what we were doing
previously, instead we were returning the first match.
Fix this by storing the first appearance of a …

repository2: get the correct layer index

---

lib/internal/backend/repository/repository2.go

With docker manifest v2.2 and oci the layers are ordered from the base layer to
the topmost layer.
This is just a quick fix for review. Next steps will be to add tests and remove duplicated layers.
Fixes #189

repository2: fix manifest v2.2 layer ordering.

---

lib/internal/internal.go

This PR changes the behavior of uid/gid translation, by re-using
uid value when available as a fallback for a missing gid.
Fixes #175

lib/internal: re-use uid value when gid is missing

---

lib/internal/backend/repository/repository2.go
lib/internal/docker/docker_functions.go

This commit fixes docker2aci pull-by-digest in order to avoid an
improper fallback to "latest" tag and a wrong comparison when no
tags have been specified.
Reference: https://github.com/coreos/rkt/issues/2313#issuecomment-245455406

lib/internal: do not compare tag when pulling by digest

---

lib/internal/backend/file/file.go
lib/internal/internal.go
lib/internal/util/util.go
lib/tests/v22_test.go
tests/test.sh

This introduces go vet, and fixes error handling in backend/file.
Fixes #194

lib/internal: fix vet errors, and error handling

---

lib/internal/backend/repository/repository.go

This commit changes version detection behavior to align with
Registry v2 specs:
```
If 404 Not Found response status, or other unexpected status,
is returned, the client should proceed with the assumption
that the registry does not implement V2 of the API.
```
Reference: https://docs.docker.com/registry/spec/api/#/api-version-check
Fixes https://github.com/appc/docker2aci/issues/85

backend/repository: assume no v2 on unexpected status

---

CHANGELOG.md
lib/version.go

This release adds support for converting local OCI bundles and fixes two security issues (CVE-2016-7569 and CVE-2016-8579). It also includes fixes for several image fetching and conversion bugs.

Release v0.13.0

---

lib/internal/backend/repository/repository.go
lib/tests/server.go

fixes #219
requires a trailing / on the v2 check URL
https://docs.docker.com/registry/spec/api/#api-version-check
some implementations are clearly stricter with the specs
https://play.golang.org/p/fNuI9iVw0S

Correct v2 registry check URL

---

lib/internal/backend/repository/repository.go
lib/internal/backend/repository/repository1.go
lib/internal/backend/repository/repository2.go

fixes #221
docker2aci would only attempt the v2 api if a registry supported it.
this check for a 404 error from the v2 api and if so attempts to
fallback to v1.
Workflow:
probe v2, try v2, downgrade-on-failure, probe v1, try v1,
hardfail-on-failure

lib/internal: allow auto fallback from v2 API to v1

---

build.sh

Pass `--always` to `git describe`, falling back to commit revision
in case tags were not fetched.
This workarounds some non-deterministic race/failure on semaphore:
```
fatal: No names found, cannot describe anything.
```

build: use git describe fallback

---

glide.lock
glide.yaml
lib/internal/internal.go
lib/internal/types/docker_types.go
vendor/github.com/appc/spec/schema/pod.go
vendor/github.com/appc/spec/schema/types/app.go
vendor/github.com/appc/spec/schema/types/isolator_linux_specific.go
vendor/github.com/appc/spec/schema/types/mountpoint.go
vendor/github.com/appc/spec/schema/types/port.go
vendor/github.com/appc/spec/schema/types/user_annotations.go
vendor/github.com/appc/spec/schema/types/user_labels.go
vendor/github.com/appc/spec/schema/types/volume.go

this is a second version of https://github.com/appc/docker2aci/pull/209!
I started out by just converting Docker labels to UserLabels. But then I realized there was a problem! Sometimes, when the Docker image doesn't have a `Cmd` in it, the labels wouldn't get converted.
So I also changed it to not require an image to have a Docker command to convert the other Docker metadata on the image. I can't see why this wouldn't work, but probably there's some reason I don't know yet that this `exec != nil` check was there in the first place.
(also I might have gotten the vendoring wrong -- I haven't used glide before)

Map Docker labels to appc UserLabels

---

lib/common/common.go
lib/internal/backend/file/file.go
lib/internal/internal.go
lib/tests/v22_test.go

Currently, there's no lossless way to actually recover this information.
e.g. if the user fetches: nginx:latest vs library/nginx:latest, the two
outputs are identical.
This provides a way to recover that input.
cc @lucab

fetch: annotate originally requested name

---

scripts/glide-update

The current glide update flags are deprecated, and the current settings
are default behavior in glide.
This fixes it.

scripts: update glide-update vendor script

---

CHANGELOG.md
lib/version.go

This release adds compatibility for OCI v1.0.0-rc2 types, introduces supports for converting image labels, and fixes some issues related to automatic fallback to registry API v1.
- log: introduce Logger interface ([#218](https://github.com/appc/docker2aci/pull/218))
- lib/internal: set UserLabels to be Docker image labels ([#223](https://github.com/appc/docker2aci/pull/223)).
- fetch: annotate originally requested name ([#224](https://github.com/appc/docker2aci/pull/224)).
- types: update OCI image-spec to rc2 ([#226](https://github.com/appc/docker2aci/pull/226)).
- lib/internal: fix v2 registry check URL ([#220](https://github.com/appc/docker2aci/pull/220))
- lib/internal: allow auto fallback from v2 API to v1 ([#222](https://github.com/appc/docker2aci/pull/222)).

Release 0.14.0

---

lib/internal/backend/file/file.go

The use case is rktlet wanting the `originalname` value when using `docker2aci` + `rkt fetch`.
Originally I figured I could use `--image=...` to have `originalname` end up there rather than guessing at it, but `--image` was broken for any images that need special handling (namely all library/ dockerhub images), and after thinking about it a bit more I think taking a guess at the originalname is okay here.
I left a fairly detailed commit comment for the most complicated of the changes, and the commits are broken up into nice bite-sized diffs.

Image from file improvements; guesses at "originalname" and fixes for "--image"

---

lib/internal/internal.go
lib/internal/internal_test.go
lib/tests/v22_test.go
tests/test.sh

This patch adds additional logic of operation system and architecture
labels translation during the conversion of Docker images to ACIs.
It also ships a set of unit tests in order to validate the changes.
References https://github.com/appc/docker2aci/issues/195

Translate "os" and "arch" labels of image manifest

---

CHANGELOG.md
lib/version.go

This is a bugfix release which improves translation of arch labels and image name.
- Translate "os" and "arch" labels of image manifest ([#234](https://github.com/appc/docker2aci/pull/234)).
- Minor style changes ([#230](https://github.com/appc/docker2aci/pull/230)).
- Bump appc/spec library version to 0.8.9 ([#233](https://github.com/appc/docker2aci/pull/233)).
- Image from file improvements; guesses at "originalname" and fixes for "--image"([#229](https://github.com/appc/docker2aci/pull/229)).

docker2aci 0.15.0

---

lib/common/common.go
lib/docker2aci.go
lib/internal/backend/file/file.go
lib/internal/backend/repository/repository.go
lib/internal/backend/repository/repository1.go
lib/internal/backend/repository/repository2.go
lib/internal/internal.go
lib/tests/v22_test.go

There are two commits in here. In order they:
1. Add an annotation to produced ACIs with a hash of the original docker manifest (or sometimes the app ID depending on the version of the HTTP API used)
2. tweaks the library API so that callers can provide a list of manifest hashes they already have
These two changes should allow for rkt to provide a list of docker manifest hashes (obtained by ACI manifest annotations) for images it already has but wants docker2aci to check for an update for. If docker2aci pulls the manifest for an image and it's in the list of images already owned by the caller, it doesn't have to download the image.
This is part of the work for https://github.com/coreos/rkt/issues/2937

Annotate manifest hash

---

lib/common/common.go
lib/common/common_test.go
lib/docker2aci.go
lib/internal/backend/repository/repository.go
lib/internal/backend/repository/repository2.go
lib/internal/typesV2/docker_types.go
lib/tests/common.go
lib/tests/v22_test.go
tests/test.sh

This commit tweaks the library's API to allow consumers to selectively
disable registry support (v1 or v2) and what mediatypes docker2aci
claims to be able to accept during an image pull (v2.1, v2.2, and oci).
By default all options are enabled, and this is still the case when
using docker2aci via the command line.
Fixes https://github.com/appc/docker2aci/issues/216.

Allow selective disabling of registries and media types

---

CHANGELOG.md
lib/version.go

This release adds a manifest hash annotation on converted images, and introduces some API changes to allow for more granular control on registries and media types.
- Annotate manifest hash ([#237](https://github.com/appc/docker2aci/pull/237)).
- Allow selective disabling of registries and media types ([#239](https://github.com/appc/docker2aci/pull/239)).
- Update appc/spec to 0.8.10 ([#242](https://github.com/appc/docker2aci/pull/242)).

docker2aci v0.16.0

---

lib/docker2aci.go

Docker allows creating empty images (e.g. with FROM scratch followed by
a no-op like MAINTAINER or LABEL).
Without this patch, docker2aci will panic when it encounters an image of
this sort.
These images are more-or-less useless. They're also difficult to work
with. As an example, `docker save` bails on them with an `unimplemented`
error.
In line with that behavior, I think bailing in docker2aci makes sense
too rather than dealing with more robust error handling or creating an
empty ACI.

Avoid panicing on scratch images

---

lib/common/common.go
lib/common/common_test.go

Some registries serve signed manifests and refuse to deliver them (error
404) unless the client specifies the correct Accept header:
$ docker2aci docker://gcr.io/google_containers/busybox:1.24
Error: conversion error: attempted fallback to API v1 but not supported
$ curl --header 'Accept: application/vnd.docker.distribution.manifest.v1+json' \
-i https://gcr.io/v2/google_containers/busybox/manifests/1.24
HTTP/2 404
docker-distribution-api-version: registry/2.0
content-type: application/json
date: Fri, 20 Oct 2017 09:29:29 GMT
server: Docker Registry
cache-control: private
x-xss-protection: 1; mode=block
x-frame-options: SAMEORIGIN
alt-svc: quic=":443"; ma=2592000; v="39,38,37,35"
accept-ranges: none
vary: Accept-Encoding
{"errors":[{"code":"MANIFEST_UNKNOWN","message":"Manifest with tag …

lib: add signed manifest media type
