appc/docker2aci

LICENSE, lib/docker2aci.go, lib/docker_functions.go, lib/docker_types.go, lib/types.go, lib/util.go, main.go, tarball/tarfile.go, tarball/walk.go
=> Add LICENSE and license headers

lib/docker2aci.go
Make sure we pass valid strings to NewACName
Fixes #12
=> Sanitize AC Names

lib/backend/file/file.go, lib/backend/repository/repository.go, lib/common/common.go, lib/conversion_store.go, lib/docker2aci.go
=> Compress layers only when not squashing

lib/backend/repository/repository.go
Google Container Registry doesn't implement the Docker registry API
correctly: when trying to access
"REGISTRY/repositories/IMAGE/NAME/tags/TAG" it fails with a 405.
Instead of getting the tag from that URL, get the JSON with all the tags
and look for the one we want. This is what Docker does.
Fixes #39
=> Fix retrieving images from Google Container Registry

README.md
=> README.md: add build information

lib/common/common.go
* author
* created
* comment
/cc @philips
=> lib/common: include annotations from docker image

MAINTAINERS
=> *: add MAINTAINERS file

README.md, lib/backend/file/file.go, lib/backend/repository/repository.go
Use ioprogress library to show a progess bar when downloading images
from a Docker repository.
For this to work correctly we need coreos/ioprogress#3
=> repository: add progress bar

lib/docker2aci.go
Fixes: https://github.com/appc/docker2aci/issues/50
=> lib: add the tmpDir parameter

lib/common/common.go
=> common: fix build by changing annotation's type to ACIdentifier

lib/docker2aci.go
We were writing the file directly to its final destination instead of
writing it to a temporary file and then renaming it. This caused file
corruption when running docker2aci several times in parallel.
We now write the squashed ACI to a temporary file with a random name and
rename it atomically after the write is finished and the ACI validated.
Fixes #73
=> lib: properly write squashed ACI to disk

lib/backend/repository/repository.go
Switched bar drawing function so that the bar will be surpressed when
not drawing to a tty.
=> Updated to use the new ioprogress library.

tests/rkt-v0.11.0.md5sum, tests/rkt-v0.12.0.md5sum, tests/test.sh
rkt now has `--insecure-options`.
=> tests: --insecure-skip-verify to --insecure-options

lib/common/common.go
This information enables users to substitute only ENTRYPOINT or CMD
alone.
cc @iaguis @alban 
Converted image image manifest now looks like:
```
$ actool cat-manifest --pretty-print google_containers-heapster_grafana-v2.1.1.aci
{
"acKind": "ImageManifest",
"acVersion": "0.7.0",
"name": "beta.gcr.io/google_containers/heapster_grafana",
"labels": [
{
"name": "version",
"value": "v2.1.1"
},
{
"name": "os",
"value": "linux"
},
{
"name": "arch",
"value": "amd64"
}
],
"app": {
"exec": [
"/bin/sh",
"-c",
"/run.sh"
],
"user": "0",
"group": "0",
"workingDirectory": "/usr/share/grafana",
"environment": [
{
"name": "PATH",
"value": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
}
],
"mountPoints": [
{
"name": "volume-etc-grafana",
"path": "/etc/grafana"
},
{
"name": …
```
=> common: Add annotations for docker ENTRYPOINT and CMD.

MAINTAINERS
The previous ones don't exist anymore.
=> MAINTAINERS: update email addresses

CHANGELOG.md, lib/version.go
=> release v0.9.1

CHANGELOG.md
=> CHANGELOG: fix typo v0.9.2 -> v0.9.3

CHANGELOG.md, lib/version.go
=> release v0.10.0

CHANGELOG.md
=> CHANGELOG: add missing bugfix entry

CHANGELOG.md, lib/version.go
=> release v0.11.0

CHANGELOG.md, lib/version.go
xref coreos/rkt#2188 (comment)
Supersedes #178
=> release 0.12.0

CHANGELOG.md, lib/version.go
=> release v0.12.2

CHANGELOG.md, lib/version.go
=> release v0.12.3

lib/internal/internal.go, lib/tests/v22_test.go
Also, refactor some code.
And add a test.
Fixes #198
=> lib/internal: add entrypoint/cmd annotations to v21 images

glide.lock, glide.yaml, lib/internal/backend/file/file.go, lib/internal/internal.go, vendor/github.com/opencontainers/image-spec/LICENSE, vendor/github.com/opencontainers/image-spec/specs-go/descriptor.go, vendor/github.com/opencontainers/image-spec/specs-go/version.go, vendor/github.com/opencontainers/image-spec/specs-go/versioned.go
This also switches to the new OCI media types.
=> Add support for converting OCI tarfiles

lib/internal/backend/repository/repository2.go, lib/internal/typesV2/docker_types.go
=> Use the new media types for oci

main.go
A few minor style changes. No change, except the `len(args)` check.
=> Minor style changes

CHANGELOG.md, lib/version.go
=> release v0.17.0

CHANGELOG.md, lib/version.go
=> release v0.17.1

lib/internal/internal.go
fix tar header format after manipulating the Name and Linkname.
Fixes: https://github.com/appc/docker2aci/issues/259
=> lib/internal: fix tar header format
